/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DOGE } from "./DOGE";
export type { LUNA } from "./LUNA";
export type { SkyMoney } from "./SkyMoney";
